// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYsPr24ea5QS5tApN1aGZECvH5lm4oVBc',
    appId: '1:132744063764:web:45dbd98c8eeab7bcd27001',
    messagingSenderId: '132744063764',
    projectId: 'ecommerceapp-55501',
    authDomain: 'ecommerceapp-55501.firebaseapp.com',
    storageBucket: 'ecommerceapp-55501.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWsDFlQSkQQfvI2rlO_0MZjwJp4GmroPk',
    appId: '1:132744063764:android:da004b0be844dfb3d27001',
    messagingSenderId: '132744063764',
    projectId: 'ecommerceapp-55501',
    storageBucket: 'ecommerceapp-55501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNiIZGkcTlcicvBUihXvT7vHuBDA2FlgA',
    appId: '1:132744063764:ios:768fc9f61821d28dd27001',
    messagingSenderId: '132744063764',
    projectId: 'ecommerceapp-55501',
    storageBucket: 'ecommerceapp-55501.firebasestorage.app',
    androidClientId: '132744063764-rgv01it8fo1no5iic4jh2vdnvbodq7fk.apps.googleusercontent.com',
    iosClientId: '132744063764-19gi2j6vopdqqvov2lo73r5c6t80bt1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

}